// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"xprem/internal/types"
)

const countBuilds = `-- name: CountBuilds :one
SELECT count(*) FROM builds WHERE app_id=$1
`

func (q *Queries) CountBuilds(ctx context.Context, appID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBuilds, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBuild = `-- name: GetBuild :one
SELECT id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at FROM builds WHERE app_id=$1 AND id=$2
`

type GetBuildParams struct {
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetBuild(ctx context.Context, arg GetBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, getBuild, arg.AppID, arg.ID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Platform,
		&i.ApplicationID,
		&i.Status,
		&i.ArtifactType,
		&i.Size,
		&i.Sha256,
		&i.ArtifactKey,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplay,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const insertBuild = `-- name: InsertBuild :one
INSERT INTO builds(id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
ON CONFLICT (id) DO NOTHING RETURNING id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at
`

type InsertBuildParams struct {
	ID              pgtype.UUID        `json:"id"`
	AppID           pgtype.UUID        `json:"app_id"`
	AppIdentifierID pgtype.UUID        `json:"app_identifier_id"`
	Platform        types.Platform     `json:"platform"`
	ApplicationID   string             `json:"application_id"`
	Status          types.BuildStatus  `json:"status"`
	ArtifactType    string             `json:"artifact_type"`
	Size            int64              `json:"size"`
	Sha256          string             `json:"sha256"`
	ArtifactKey     string             `json:"artifact_key"`
	Metadata        []byte             `json:"metadata"`
	ActorType       string             `json:"actor_type"`
	ActorID         string             `json:"actor_id"`
	ActorDisplay    string             `json:"actor_display"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	DurationMs      *int64             `json:"duration_ms"`
}

func (q *Queries) InsertBuild(ctx context.Context, arg InsertBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, insertBuild,
		arg.ID,
		arg.AppID,
		arg.AppIdentifierID,
		arg.Platform,
		arg.ApplicationID,
		arg.Status,
		arg.ArtifactType,
		arg.Size,
		arg.Sha256,
		arg.ArtifactKey,
		arg.Metadata,
		arg.ActorType,
		arg.ActorID,
		arg.ActorDisplay,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Platform,
		&i.ApplicationID,
		&i.Status,
		&i.ArtifactType,
		&i.Size,
		&i.Sha256,
		&i.ArtifactKey,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplay,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const listBuilds = `-- name: ListBuilds :many
SELECT id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at FROM builds WHERE app_id=$1 ORDER BY created_at DESC,id DESC LIMIT $2 OFFSET $3
`

type ListBuildsParams struct {
	AppID  pgtype.UUID `json:"app_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListBuilds(ctx context.Context, arg ListBuildsParams) ([]Build, error) {
	rows, err := q.db.Query(ctx, listBuilds, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AppIdentifierID,
			&i.Platform,
			&i.ApplicationID,
			&i.Status,
			&i.ArtifactType,
			&i.Size,
			&i.Sha256,
			&i.ArtifactKey,
			&i.Metadata,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplay,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBuild = `-- name: LockBuild :one
SELECT id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at FROM builds WHERE app_id=$1 AND id=$2 FOR UPDATE
`

type LockBuildParams struct {
	AppID pgtype.UUID `json:"app_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) LockBuild(ctx context.Context, arg LockBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, lockBuild, arg.AppID, arg.ID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Platform,
		&i.ApplicationID,
		&i.Status,
		&i.ArtifactType,
		&i.Size,
		&i.Sha256,
		&i.ArtifactKey,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplay,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const updateBuild = `-- name: UpdateBuild :one
UPDATE builds SET status=$3, size=$4, sha256=$5, metadata=$6, finished_at=$7, duration_ms=$8,
    ready_at=CASE WHEN $3='ready' THEN COALESCE(ready_at, now()) ELSE NULL END, updated_at=now()
WHERE app_id=$1 AND id=$2 RETURNING id, app_id, app_identifier_id, platform, application_id, status, artifact_type, size, sha256, artifact_key, metadata, actor_type, actor_id, actor_display, started_at, finished_at, duration_ms, created_at, updated_at, ready_at
`

type UpdateBuildParams struct {
	AppID      pgtype.UUID        `json:"app_id"`
	ID         pgtype.UUID        `json:"id"`
	Status     types.BuildStatus  `json:"status"`
	Size       int64              `json:"size"`
	Sha256     string             `json:"sha256"`
	Metadata   []byte             `json:"metadata"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs *int64             `json:"duration_ms"`
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, updateBuild,
		arg.AppID,
		arg.ID,
		arg.Status,
		arg.Size,
		arg.Sha256,
		arg.Metadata,
		arg.FinishedAt,
		arg.DurationMs,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AppIdentifierID,
		&i.Platform,
		&i.ApplicationID,
		&i.Status,
		&i.ArtifactType,
		&i.Size,
		&i.Sha256,
		&i.ArtifactKey,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplay,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}
