// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: build_logs.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buildLogEndOffset = `-- name: BuildLogEndOffset :one
SELECT COALESCE((SELECT byte_offset + octet_length(content) FROM build_log_chunks
WHERE build_id=$1 ORDER BY byte_offset DESC LIMIT 1), 0)::integer AS end_offset
`

func (q *Queries) BuildLogEndOffset(ctx context.Context, buildID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, buildLogEndOffset, buildID)
	var end_offset int32
	err := row.Scan(&end_offset)
	return end_offset, err
}

const getBuildLogChunk = `-- name: GetBuildLogChunk :one
SELECT content, format FROM build_log_chunks WHERE build_id=$1 AND byte_offset=$2
`

type GetBuildLogChunkParams struct {
	BuildID    pgtype.UUID `json:"build_id"`
	ByteOffset int32       `json:"byte_offset"`
}

type GetBuildLogChunkRow struct {
	Content string `json:"content"`
	Format  string `json:"format"`
}

func (q *Queries) GetBuildLogChunk(ctx context.Context, arg GetBuildLogChunkParams) (GetBuildLogChunkRow, error) {
	row := q.db.QueryRow(ctx, getBuildLogChunk, arg.BuildID, arg.ByteOffset)
	var i GetBuildLogChunkRow
	err := row.Scan(&i.Content, &i.Format)
	return i, err
}

const insertBuildLogChunk = `-- name: InsertBuildLogChunk :exec
INSERT INTO build_log_chunks(build_id, byte_offset, content, format) VALUES ($1,$2,$3,$4)
`

type InsertBuildLogChunkParams struct {
	BuildID    pgtype.UUID `json:"build_id"`
	ByteOffset int32       `json:"byte_offset"`
	Content    string      `json:"content"`
	Format     string      `json:"format"`
}

func (q *Queries) InsertBuildLogChunk(ctx context.Context, arg InsertBuildLogChunkParams) error {
	_, err := q.db.Exec(ctx, insertBuildLogChunk,
		arg.BuildID,
		arg.ByteOffset,
		arg.Content,
		arg.Format,
	)
	return err
}

const listBuildLogChunks = `-- name: ListBuildLogChunks :many
SELECT l.byte_offset, l.content, l.format, l.created_at FROM build_log_chunks l
JOIN builds b ON b.id=l.build_id
WHERE b.app_id=$1 AND l.build_id=$2 AND l.byte_offset >= $3
ORDER BY l.byte_offset LIMIT 32
`

type ListBuildLogChunksParams struct {
	AppID      pgtype.UUID `json:"app_id"`
	BuildID    pgtype.UUID `json:"build_id"`
	ByteOffset int32       `json:"byte_offset"`
}

type ListBuildLogChunksRow struct {
	ByteOffset int32              `json:"byte_offset"`
	Content    string             `json:"content"`
	Format     string             `json:"format"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListBuildLogChunks(ctx context.Context, arg ListBuildLogChunksParams) ([]ListBuildLogChunksRow, error) {
	rows, err := q.db.Query(ctx, listBuildLogChunks, arg.AppID, arg.BuildID, arg.ByteOffset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildLogChunksRow
	for rows.Next() {
		var i ListBuildLogChunksRow
		if err := rows.Scan(
			&i.ByteOffset,
			&i.Content,
			&i.Format,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
